export const WORD_POOL = [
  // Películas y series
  "el padrino",
  "breaking bad",
  "shrek",
  "toy story",
  "matrix",
  "star wars",
  "harry potter",
  "batman",
  "spiderman",
  "terminator",
  "titanic",
  "volver al futuro",
  "el señor de los anillos",
  "game of thrones",
  "los simpson",
  "dragon ball",
  "pokemon",
  "naruto",
  "avengers",
  "deadpool",
  "futurama",
  "rick y morty",
  "stranger things",
  "the office",
  "friends",
  "the big bang theory",
  "black mirror",
  "bart simpsons",
  "homer simpsons",
  "lisa simpsons",
  "marge simpsons",

  // Sistemas / IT
  "pantalla azul",
  "windows xp",
  "linux",
  "ubuntu",
  "servidor caido",
  "reiniciar router",
  "wifi lento",
  "base de datos",
  "sql",
  "bug en produccion",
  "deploy viernes",
  "merge conflict",
  "docker",
  "kubernetes",
  "git push --force",
  "hacker",
  "firewall",
  "vpn",
  "azure",
  "aws",
  "jira",
  "scrum",
  "devops",
  "backend",
  "frontend",
  "full stack",
  "microservicios",
  "api rota",
  "token vencido",
  "404 not found",
  "500 internal server error",
  "captcha",
  "phishing",
  "ciberseguridad",
  "codigo spaghetti",
  "excel en produccion",
  "copilot",
  "chatgpt",
  "inteligencia artificial",

  // Random / divertidas
  "milanesa con papas fritas",
  "asado",
  "morcilla",
  "birra artesanal",
  "cafe con leche",
  "padel",
  "motoneta",
  "gemelos",
  "vomitado y recien levantado",
  "la monica",
  "chancla voladora",
  "vecino chusma",
  "trafico en hora pico",
  "mate lavado",
  "empanada de carne",
  "suegra",
  "teletrabajo",
  "oficina open space",
  "lunes a las 8am",
  "programador sin dormir",
  "reunion que pudo ser mail",
  "teclado mecanico",
  "mouse gamer",
  "streamer",
  "influencer",
  "crypto bro",
  "memes",
  "perro programador",
  "gato sobre teclado",
];

/**
 * Returns a random word from the WORD_POOL.
 */
export const randomWord = () => {
  return WORD_POOL[Math.floor(Math.random() * WORD_POOL.length)];
};

